### ISSUE TITLE
metadata recommendation documents/urls

### ISSUE THREAD

**Issue by kf8a** [lter/im-manual#11]
Should there be a place here for metadata recommendations such as  https://ediorg.github.io/data-package-best-practices/? i was looking at https://lter.github.io/im-manual/new-to-im and https://lter.github.io/im-manual/eml,, but I don't know where most people would be looking for it.

**Comment by twhiteaker** [comment]
The data package best practices document is linked from the second sentence on the EML page.  Since the BP document is broader than EML, and since making data packages is one the primary responsibilities of the IM, I think the document should also be linked from the New To IM page.  I would insert it as the second bullet under Key Resources.  Separate issue, but I would also move the Retired IM Website bullet to the bottom of Key Resources.

Does that plan sound logical to you, @kf8a ?

**Comment by marty-downs** [comment]
Assuming that the edits @twhiteaker completed resolve the issue.
